spring.application.name=Backend

# For a real H2 testing with reloads, leaving here for extra versions

# H2 File-based Database URL
#spring.datasource.url=jdbc:h2:file:./data/bookdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# JPA / Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update

# H2 Web Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
